### ISSUE TITLE
Теперь точно удаляй

### ISSUE THREAD

**Issue by AlekseyBulaev** [andrei-punko/java-interview-coding#18]
```
public enum EventType {
    SOME_EVENT("someEvent") { @Override public String parse(byte[] data) {throw new UnsupportedOperationException();}},
    SOME_OTHER_EVENT("someOtherEvent") { @Override public String parse(byte[] data) {throw new UnsupportedOperationException();}},
    ONE_MORE_EVENT("oneMoreEvent"){ @Override public String parse(byte[] data) {throw new UnsupportedOperationException();}};
    final String type;
    public String parse(byte[] data) {throw new UnsupportedOperationException();}
    EventType(String type) {
        this.type = type;
    }
    public static EventType getByValue(String value) {
        return Arrays.stream(EventType.values())
                .filter(typeValue -> typeValue.type.equalsIgnoreCase(value))
                .findFirst()
                .orElseThrow(NoSuchElementException::new);
    }
}
```

```
public class EventParser {

    public List<String> parse(List<Event> events) {
        return events.stream()
                .map(event -> EventType.getByValue(event.getType()).parse(event.getData()))
                .collect(Collectors.toList());
    }
}
```

**Comment by andrei-punko** [comment]
On each call of `EventParser.parse()` you make for each event from list call of `getByValue()`.
In `EventType.getByValue()` you go through all values of `EventType` and make comparisons each time.

This approach isn't effective because `EventType's` values() known at the start of application and we could make some pre-calculations to avoid make it again and again each time.

**Comment by AlekseyBulaev** [comment]
Это  решается так же без добавления рефлексии.

```
    Map<String, EventType> types = Arrays.stream(EventType.values())
            .collect(Collectors.toMap(typeValue -> typeValue.type, type -> type));

    public List<String> parse(List<Event> events) {
        return events.stream()
                .map(event -> types.get(event.getType()).parse(event.getData()))
                .collect(Collectors.toList());
    }
```
При этом твой код меняет модель со String на EventType - что в большинстве проектов сделать очень сложно, почти невозможно. Работу по маппингу стринги на событие кто-то тоже делает.

но если мы поменяем модель со стринг на енум

```
    public List<String> parse(List<Event> events) {
        return events.stream()
                .map(event -> event.getType().parse(event.getData()))
                .collect(Collectors.toList());
    }
```

Так же в замечание тебе укажу - отсутствие тестов, что не показатель высокой культуры в разработке.

**Comment by andrei-punko** [comment]
Мой код меняет String на Enum **сознательно**, чтобы снизить вариативность значений для будущих разработчиков, сковать им руки, чтобы исключить ошибки в будущем, потому что в String поле можно положить что угодно, а в Enum поле - только значения из предефайнутого набора.

Обвинять меня  в том, что я не пишу тесты - это немного смешно:
- посмотрите JaCoCo репорт - общее покрытие более 90%
- все видео забиты тестами, в некоторых на тесты тратится больше времени чем на имплементацию
- **этот рефакторинг был не про это**; неужели вы думаете, что я не могу написать тесты для двух примитивных публичных методов, тогда как написал тесты для сотен других в этом же репо?

Также - называть issue "Теперь точно удаляй" - это непрофессионально, и не есть "показатель высокой культуры разработки"

Спасибо в общем за дискуссию, хотя на "ты" я не переходил

**Comment by AlekseyBulaev** [comment]
Простите меня.
Я, видимо, Вас, как-то задел.

Вы правы, я не профессионал, поэтому и не вещаю на весь мир.

Я вам показал решение, которое по моему мнению лучше вашего. Вы попросили код, я вам его предоставил, но вы цепляетесь к моментам, которые никак не связаны с решением
Мое решение:
- не добавляет оверхеда
- гораздо лучше спроектировано (cohesion & coupling/ law of demeter)
- проще поддерживать (при добавлении нового типа, нам не нужно создавать новую имплементацию интерфейса, который и не нужен)
-  проще тестировать

**Comment by andrei-punko** [comment]
Follow-up по итогам взаимодействия:
- Убрал просьбу предоставить вариант кода, т.к. это было сделано: https://www.youtube.com/watch?v=jdnNYxVk5BE
- Удалил коммент о том, что "это мое любимое видео": https://www.youtube.com/watch?v=jdnNYxVk5BE
- Добавил тесты для существующего решения: https://github.com/andrei-punko/java-interview-coding/commit/c43a55bbc797fbf8b9d856453601890e3546f0ce
